
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

export default function Office(props) {
  const { nodes, materials } = useGLTF("/models/office.glb");
  return (
    <RigidBody type="fixed" colliders="trimesh">
      <group {...props} dispose={null}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_1.geometry}
            material={materials["wood.004"]}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh001.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh001_1.geometry}
            material={materials["wood.004"]}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh006.geometry}
            material={materials["01 - Default"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh006_1.geometry}
            material={materials.OfficeChair_Modern}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh007.geometry}
            material={materials["01 - Default"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh007_1.geometry}
            material={materials.OfficeChair_Modern}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cabinet1001.geometry}
          material={materials["wood 4"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cabinet1002.geometry}
            material={materials["wood 4"]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cabinet1_Door002.geometry}
              material={materials["wood 4"]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Handle002.geometry}
                material={materials.Metal}
              />
            </mesh>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Countertop1002.geometry}
              material={materials["wood 4"]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh014.geometry}
                material={materials.Monitor_01}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_1.geometry}
                material={materials["printer Grey "]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh014_2.geometry}
                material={materials["printer Buttons Black"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube177.geometry}
                material={materials["printer Buttons Black"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube178.geometry}
                material={materials["printer Buttons Black"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube179.geometry}
                material={materials["printer Buttons Black"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube180.geometry}
                material={materials["printer Button ON/OFF"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh013.geometry}
                material={materials.floor}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh013_1.geometry}
                material={materials.Paper}
              />
            </mesh>
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cabinet1_Door001.geometry}
            material={materials["wood 4"]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Handle001.geometry}
              material={materials.Metal}
            />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Countertop1001.geometry}
            material={materials["wood 4"]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cabinet1011.geometry}
          material={materials["Grey shelfes"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cabinet1012.geometry}
            material={materials["Grey shelfes"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cabinet1013.geometry}
            material={materials["Grey shelfes"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube165.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube166.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube167.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube168.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube169.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube176.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh023.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh023_1.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh024.geometry}
            material={materials["BOOKS 2"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh024_1.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh025.geometry}
            material={materials["BOOKS 3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh025_1.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh026.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh026_1.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh027.geometry}
            material={materials["BOOKS 3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh027_1.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh028.geometry}
            material={materials["BOOKS 3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh028_1.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh029.geometry}
            material={materials["BOOKS 3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh029_1.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh030.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh030_1.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh031.geometry}
            material={materials["BOOKS 2"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh031_1.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh032.geometry}
            material={materials["BOOKS 3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh032_1.geometry}
            material={materials.Monitor_01}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cabinet1014.geometry}
          material={materials["Grey shelfes"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cabinet1015.geometry}
            material={materials["Grey shelfes"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cabinet1016.geometry}
            material={materials["Grey shelfes"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube170.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube171.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube172.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube173.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube174.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube175.geometry}
            material={materials["Black plastic"]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cabinet1017.geometry}
          material={materials["wood 4"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cabinet1018.geometry}
            material={materials["wood 4"]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cabinet1_Door012.geometry}
              material={materials["wood 4"]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Handle012.geometry}
                material={materials.Metal}
              />
            </mesh>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Countertop1006.geometry}
              material={materials["wood 4"]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mug1002.geometry}
                material={materials["Pam desk"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh056.geometry}
                material={materials.Monitor_01}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh056_1.geometry}
                material={materials["printer Grey "]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh056_2.geometry}
                material={materials["printer Buttons Black"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube185.geometry}
                material={materials["printer Button ON/OFF"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube186.geometry}
                material={materials["printer Buttons Black"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube187.geometry}
                material={materials["printer Buttons Black"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube188.geometry}
                material={materials["printer Buttons Black"]}
              />
            </mesh>
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cabinet1_Door011.geometry}
            material={materials["wood 4"]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Handle011.geometry}
              material={materials.Metal}
            />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Countertop1005.geometry}
            material={materials["wood 4"]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cabinet1027.geometry}
          material={materials["wood 4"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube203.geometry}
            material={materials.Paper}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube204.geometry}
            material={materials.Paper}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube205.geometry}
            material={materials.Paper}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh065.geometry}
            material={materials["BOOKS 3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh065_1.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh065_2.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh065_3.geometry}
            material={materials["Pam desk"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh065_4.geometry}
            material={materials["BOOKS 2"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh066.geometry}
            material={materials["BOOKS 2"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh066_1.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh067.geometry}
            material={materials["BOOKS 3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh067_1.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh072.geometry}
            material={materials.floor}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh072_1.geometry}
            material={materials["Grey shelfes"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh073.geometry}
            material={materials.floor}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh073_1.geometry}
            material={materials["Grey shelfes"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh071.geometry}
            material={materials.floor}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh071_1.geometry}
            material={materials.Paper}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cabinet1028.geometry}
          material={materials["wood 4"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cabinet1029.geometry}
            material={materials["wood 4"]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cabinet1_Door022.geometry}
              material={materials["wood 4"]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Handle022.geometry}
                material={materials.Metal}
              />
            </mesh>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Countertop1004.geometry}
              material={materials["wood 4"]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh080.geometry}
                material={materials.Monitor_01}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh080_1.geometry}
                material={materials["printer Grey "]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh080_2.geometry}
                material={materials["printer Buttons Black"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube199.geometry}
                material={materials["printer Button ON/OFF"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube200.geometry}
                material={materials["printer Buttons Black"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube201.geometry}
                material={materials["printer Buttons Black"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube202.geometry}
                material={materials["printer Buttons Black"]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh079.geometry}
                material={materials.floor}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh079_1.geometry}
                material={materials.Paper}
              />
            </mesh>
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cabinet1_Door021.geometry}
            material={materials["wood 4"]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Handle021.geometry}
              material={materials.Metal}
            />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Countertop1003.geometry}
            material={materials["wood 4"]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cabinet1030.geometry}
          material={materials["wood 4"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube206.geometry}
            material={materials.Paper}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube207.geometry}
            material={materials.Paper}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube208.geometry}
            material={materials.Paper}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh089.geometry}
            material={materials["BOOKS 3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh089_1.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh089_2.geometry}
            material={materials["BOOKS 2"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh089_3.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh090.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh090_1.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh091.geometry}
            material={materials["BOOKS 3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh091_1.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh095.geometry}
            material={materials.Baseboard_material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh095_1.geometry}
            material={materials["Grey shelfes"]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cabinet1031.geometry}
          material={materials["wood 4"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube209.geometry}
            material={materials.Paper}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube210.geometry}
            material={materials.Paper}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube211.geometry}
            material={materials.Paper}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh097.geometry}
            material={materials["BOOKS 3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh097_1.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh097_2.geometry}
            material={materials["BOOKS 2"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh097_3.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh098.geometry}
            material={materials["BOOKS 2"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh098_1.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh099.geometry}
            material={materials["BOOKS 3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh099_1.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh104.geometry}
            material={materials.floor}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh104_1.geometry}
            material={materials["Grey shelfes"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh105.geometry}
            material={materials.floor}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh105_1.geometry}
            material={materials["Grey shelfes"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh103.geometry}
            material={materials.floor}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh103_1.geometry}
            material={materials.Paper}
          />
        </mesh>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh106.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh106_1.geometry}
            material={materials["printer Buttons Black"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh106_2.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.ClockArm.geometry}
            material={materials["printer Buttons Black"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.ClockArm001.geometry}
            material={materials["printer Buttons Black"]}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh109.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh109_1.geometry}
            material={materials["printer Buttons Black"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh109_2.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.ClockArm002.geometry}
            material={materials["printer Buttons Black"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.ClockArm003.geometry}
            material={materials["printer Buttons Black"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube212.geometry}
          material={materials["wood 4"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube215.geometry}
          material={materials["wood 4"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube216.geometry}
          material={materials["wood 4"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube217.geometry}
          material={materials["wood 4"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube218.geometry}
          material={materials["wood 4"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube219.geometry}
          material={materials["wood 4"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh118.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh118_1.geometry}
            material={materials["Poster office"]}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh119.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh119_1.geometry}
            material={materials["Poster office 2"]}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh120.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh120_1.geometry}
            material={materials["Poster office 3"]}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh121.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh121_1.geometry}
            material={materials["Poster cert"]}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh122.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh122_1.geometry}
            material={materials["Poster cert.001"]}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh123.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh123_1.geometry}
            material={materials["Poster cert.002"]}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh124.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh124_1.geometry}
            material={materials["Poster office 3"]}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh125.geometry}
            material={materials["wood 4"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh125_1.geometry}
            material={materials["Poster Pam"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube231.geometry}
          material={materials["Black plastic"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube232.geometry}
          material={materials["Black plastic"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube233.geometry}
          material={materials["Black plastic"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube234.geometry}
          material={materials["Black plastic"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Desk006.geometry}
          material={materials.wood}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube083.geometry}
            material={materials.wood}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube084.geometry}
              material={materials.Metal}
            />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh133.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh133_1.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder005.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh138.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh138_1.geometry}
            material={materials["printer Buttons Black"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh138_2.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh135.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh135_1.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh136.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh136_1.geometry}
            material={materials["Monitor screen"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh136_2.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh136_3.geometry}
            material={materials["Monitor.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh137.geometry}
            material={materials.OfficeChair_Modern}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh137_1.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh137_2.geometry}
            material={materials["Pam desk"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh137_3.geometry}
            material={materials.Metal}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Desk014.geometry}
          material={materials.wood}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube086.geometry}
            material={materials.wood}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube087.geometry}
              material={materials.Metal}
            />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh142.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh142_1.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder006.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh147.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh147_1.geometry}
            material={materials["printer Buttons Black"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh147_2.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh144.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh144_1.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh145.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh145_1.geometry}
            material={materials["Monitor screen"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh145_2.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh145_3.geometry}
            material={materials["Monitor.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh146.geometry}
            material={materials.OfficeChair_Modern}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh146_1.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh146_2.geometry}
            material={materials["Pam desk"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh146_3.geometry}
            material={materials.Metal}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Desk019.geometry}
          material={materials.wood}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.b_e_low004.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube101.geometry}
            material={materials.wood}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube102.geometry}
              material={materials.Metal}
            />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube197.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.u_a_low004.geometry}
            material={materials.Monitor_01_Decals}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.b_a_low004.geometry}
              material={materials.Monitor_01_Decals}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.b_b_low004.geometry}
              material={materials.Monitor_01_Decals}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.b_c_low004.geometry}
              material={materials.Monitor_01_Decals}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.b_d_low004.geometry}
              material={materials.Monitor_01_Decals}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.l_a_low004.geometry}
              material={materials.Monitor_01_Decals}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.l_b_low004.geometry}
              material={materials.Monitor_01_Decals}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.l_c_low004.geometry}
              material={materials.Monitor_01_Decals}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.l_d_low004.geometry}
              material={materials.Monitor_01_Decals}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.u_c_low004.geometry}
              material={materials.Monitor_01_Decals}
            />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh151.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh151_1.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder011.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh158.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh158_1.geometry}
            material={materials["printer Buttons Black"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh158_2.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh154.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh154_1.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh155.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh155_1.geometry}
            material={materials["Monitor screen"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh155_2.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh155_3.geometry}
            material={materials["Monitor.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh156.geometry}
            material={materials.OfficeChair_Modern}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh156_1.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh156_2.geometry}
            material={materials["Pam desk"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh156_3.geometry}
            material={materials.Metal}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Door001.geometry}
          material={materials["wood.002"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DoorFrame009.geometry}
          material={materials["wood 4"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh171.geometry}
            material={materials["wood.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh171_1.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Handle_Back009.geometry}
            material={materials.Handle_material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Handle_Front009.geometry}
            material={materials.Handle_material}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Floor.geometry}
          material={materials["floor.001"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh175.geometry}
            material={materials["wood.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh175_1.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Handle_Back011.geometry}
            material={materials.Handle_material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Handle_Front011.geometry}
            material={materials.Handle_material}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DoorFrame011.geometry}
          material={materials["wood 4"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Meeting_table.geometry}
          material={materials["wood 4"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube213.geometry}
            material={materials.Metal}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder025.geometry}
              material={materials.Metal}
            />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube220.geometry}
            material={materials.Metal}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder026.geometry}
              material={materials.Metal}
            />
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh180.geometry}
            material={materials["01 - Default"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh180_1.geometry}
            material={materials.OfficeChair_Modern}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh181.geometry}
            material={materials["01 - Default"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh181_1.geometry}
            material={materials.OfficeChair_Modern}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh182.geometry}
            material={materials["01 - Default"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh182_1.geometry}
            material={materials.OfficeChair_Modern}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh183.geometry}
            material={materials["01 - Default"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh183_1.geometry}
            material={materials.OfficeChair_Modern}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh184.geometry}
            material={materials["01 - Default"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh184_1.geometry}
            material={materials.OfficeChair_Modern}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh185.geometry}
            material={materials["01 - Default"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh185_1.geometry}
            material={materials.OfficeChair_Modern}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh186.geometry}
            material={materials["01 - Default"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh186_1.geometry}
            material={materials.OfficeChair_Modern}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh187.geometry}
            material={materials["01 - Default"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh187_1.geometry}
            material={materials.OfficeChair_Modern}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh188.geometry}
            material={materials["01 - Default"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh188_1.geometry}
            material={materials.OfficeChair_Modern}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Office_Chair_Final_PBR.geometry}
          material={materials.Office_Chair}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Projector.geometry}
          material={materials.Projector}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Projector_Screen.geometry}
          material={materials["Material #27"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Remote.geometry}
          material={materials["Projector.001"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Baseboard.geometry}
          material={materials.Baseboard_material}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Room.geometry}
          material={materials.Wall_material}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.01, 0.01, 0.013]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Baseboard001.geometry}
          material={materials.Baseboard_material}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Room001.geometry}
          material={materials.Wall_material}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.01, 0.01, 0.013]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Room002.geometry}
          material={materials.Wall_material}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.01, 0.01, 0.013]}
        />
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh203.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh203_1.geometry}
            material={materials.Plastic}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh203_2.geometry}
            material={materials.Glass}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.CTRL_Hole.geometry}
          material={materials.hidden_material}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.simple_desk000.geometry}
          material={materials["wood.005"]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.b_a_low007.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.b_a_low008.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.b_b_low007.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.b_b_low008.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.b_c_low007.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.b_c_low008.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.b_d_low007.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.b_d_low008.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.b_e_low007.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.b_e_low008.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube198.geometry}
            material={materials.Paper}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.l_a_low007.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.l_a_low008.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.l_b_low007.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.l_b_low008.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.l_c_low007.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.l_c_low008.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.l_d_low007.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.l_d_low008.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.u_a_low007.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.u_a_low008.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.u_c_low007.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.u_c_low008.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh206.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh206_1.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder010.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh223.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh223_1.geometry}
            material={materials["printer Buttons Black"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh223_2.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh209.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh209_1.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh210.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh210_1.geometry}
            material={materials["Monitor screen"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh210_2.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh210_3.geometry}
            material={materials["Monitor.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh211.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh211_1.geometry}
            material={materials["Monitor screen"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh211_2.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh211_3.geometry}
            material={materials["Monitor.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh212.geometry}
            material={materials["printer White"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh212_1.geometry}
            material={materials.Coffee}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.u_a_low005.geometry}
          material={materials.Monitor_01_Decals}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.b_a_low005.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.b_b_low005.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.b_c_low005.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.b_d_low005.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.b_e_low005.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.l_a_low005.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.l_b_low005.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.l_c_low005.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.l_d_low005.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.u_c_low005.geometry}
            material={materials.Monitor_01_Decals}
          />
        </mesh>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh247.geometry}
            material={materials["wood.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh247_1.geometry}
            material={materials["wood 4.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh247_2.geometry}
            material={materials["Handle_material.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh248.geometry}
            material={materials["wood.004"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh248_1.geometry}
            material={materials.Handle_material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh249.geometry}
            material={materials["wood.004"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh249_1.geometry}
            material={materials.Handle_material}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh250.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh250_1.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh250_2.geometry}
            material={materials["printer Button ON/OFF"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh250_3.geometry}
            material={materials["BOOKS 3"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder024.geometry}
            material={materials["Water bottle"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Room1.geometry}
          material={materials.Wall_material}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.01, 0.01, 0.013]}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Baseboard003.geometry}
            material={materials.Baseboard_material}
          />
        </mesh>
        <group
          position={[1.446, 0, 0.169]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.b_a_low002.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.b_b_low002.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.b_c_low002.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.b_d_low002.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.b_e_low002.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube022.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube023.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube071.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube072.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder001.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Desk002.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Desk010.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.l_a_low002.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.l_b_low002.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.l_c_low002.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.l_d_low002.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.paper.geometry}
            material={materials.Paper}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.u_a_low002.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.u_c_low002.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh273.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh273_1.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh279.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh279_1.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh267.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh267_1.geometry}
            material={materials["printer Buttons Black"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh267_2.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh261.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh261_1.geometry}
            material={materials["printer Buttons Black"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh261_2.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh275.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh275_1.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh270.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh270_1.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh268.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh268_1.geometry}
            material={materials["Monitor screen"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh268_2.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh268_3.geometry}
            material={materials["Monitor.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh259.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh259_1.geometry}
            material={materials["Monitor screen"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh259_2.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh259_3.geometry}
            material={materials["Monitor.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh278.geometry}
            material={materials.OfficeChair_Modern}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh278_1.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh278_2.geometry}
            material={materials["Pam desk"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh278_3.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh260.geometry}
            material={materials.OfficeChair_Modern}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh260_1.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh260_2.geometry}
            material={materials["Pam desk"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh260_3.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh265.geometry}
            material={materials.floor}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh265_1.geometry}
            material={materials.Paper}
          />
        </group>
        <group
          position={[0.582, 0, 0.372]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.b_a_low003.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.b_b_low003.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.b_c_low003.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.b_d_low003.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.b_e_low003.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube074.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube075.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube077.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube078.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube080.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube081.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube196.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder002.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder003.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Desk003.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Desk004.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Desk005.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.l_a_low003.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.l_b_low003.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.l_c_low003.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.l_d_low003.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.u_a_low003.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.u_c_low003.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh301.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh301_1.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh312.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh312_1.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh300.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh300_1.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh293.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh293_1.geometry}
            material={materials["printer Buttons Black"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh293_2.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh288.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh288_1.geometry}
            material={materials["printer Buttons Black"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh288_2.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh297.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh297_1.geometry}
            material={materials["printer Buttons Black"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh297_2.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh286.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh286_1.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh296.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh296_1.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh289.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh289_1.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh294.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh294_1.geometry}
            material={materials["Monitor screen"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh294_2.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh294_3.geometry}
            material={materials["Monitor.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh315.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh315_1.geometry}
            material={materials["Monitor screen"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh315_2.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh315_3.geometry}
            material={materials["Monitor.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh320.geometry}
            material={materials.Monitor_01}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh320_1.geometry}
            material={materials["Monitor screen"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh320_2.geometry}
            material={materials.Monitor_01_Decals}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh320_3.geometry}
            material={materials["Monitor.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh308.geometry}
            material={materials.floor}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh308_1.geometry}
            material={materials.Coffee}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh290.geometry}
            material={materials.OfficeChair_Modern}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh290_1.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh290_2.geometry}
            material={materials["Pam desk"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh290_3.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh303.geometry}
            material={materials.OfficeChair_Modern}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh303_1.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh303_2.geometry}
            material={materials["Pam desk"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh303_3.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh302.geometry}
            material={materials.OfficeChair_Modern}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh302_1.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh302_2.geometry}
            material={materials["Pam desk"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh302_3.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh319.geometry}
            material={materials.floor}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh319_1.geometry}
            material={materials.Paper}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.013]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh326.geometry}
            material={materials["wood.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh326_1.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh326_2.geometry}
            material={materials.Glass}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh326_3.geometry}
            material={materials["wood 4"]}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.013]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh327.geometry}
            material={materials["wood 4"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh327_1.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh327_2.geometry}
            material={materials.Glass}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.013]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh328.geometry}
            material={materials["wood 4"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh328_1.geometry}
            material={materials["Black plastic"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh328_2.geometry}
            material={materials.Glass}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh328_3.geometry}
            material={materials.Handle_material}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh329.geometry}
            material={materials["wood 4"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh329_1.geometry}
            material={materials["wood.002"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh329_2.geometry}
            material={materials.wood}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh329_3.geometry}
            material={materials.Handle_material}
          />
        </group>
        <group
          position={[1.446, 0, 0.169]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group
            position={[-568.821, -820.186, -0.549]}
            rotation={[0, 0, -0.736]}
            scale={1.306}
          >
            <RigidBody type="dynamic" colliders="trimesh">
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Mesh002.geometry}
                material={materials["OfficeChair_Modern.001"]}
              />
            </RigidBody>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Mesh002_1.geometry}
              material={materials["Black plastic.001"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Mesh002_2.geometry}
              material={materials["Pam desk.001"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Mesh002_3.geometry}
              material={materials["Metal.001"]}
            />
          </group>
        </group>
        <group
          position={[0, 2.676, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh004.geometry}
            material={materials.Wall_material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh004_1.geometry}
            material={materials["Material.001"]}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh003.geometry}
          material={materials.Fronds}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh003_1.geometry}
          material={materials.Stalks}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh003_2.geometry}
          material={materials.Flowers}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh005.geometry}
          material={materials.Fronds}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh005_1.geometry}
          material={materials.Stalks}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mesh005_2.geometry}
          material={materials.Flowers}
        />
      </group>
    </RigidBody>
  );
}

useGLTF.preload("/models/office.glb");
